import type { Metadata } from 'next'
import { Fira_Sans } from 'next/font/google'
import './globals.css'
import Header from './Header'


const inter = Fira_Sans({weight:'400' , subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Portfolio',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
      <Header/>
        {children}
        </body>
    </html>
  )
}
